from pathlib import Path
from .djbs_constants import *

BASE_DIR = Path(__file__).resolve().parent.parent

DJBSTHEME_DEFAULTS = {
    "SEARCH_URL": None,
    "SEARCH_PARAM": None,
    "MENU_FILE": BASE_DIR / "menu_conf.yaml",
    "CHECK_AS_SWITCH": True,
    "FILTER_STYLE": FILTER_STYLE_CLASSIC,
    "FIELDSET_STYLE": STYLE_CARD,
    "INLINESET_STYLE": STYLE_CARD,
    "BADGERIZE_FACETS": True,
    "STACKED_COLS": 2,
    "HIDE_ORIGINAL": False,
    "ICON_SOURCE": "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css",
    "ICON_TAG_PATTERN": '<i class="{icon} {classes}" {attrs}></i>',
    "ICONS": {
        "add": "bi bi-plus-square",
        "alert": "bi bi-exclamation-circle",
        "back": "bi bi-arrow-left-short",
        "badge": "bi bi-person-badge",
        "building": "bi bi-buildings",
        "calendar": "bi bi-calendar-week",
        "check": "bi bi-check2",
        "check-all": "bi bi-check-all",
        "chevron-left": "bi bi-chevron-left",
        "chevron-right": "bi bi-chevron-right",
        "cloud": "bi bi-cloud-fog2",
        "config": "bi bi-gear",
        "copy": "bi bi-copy",
        "csv": "bi bi-filetype-csv",
        "database": "bi bi-database",
        "default": "bi bi-wrench-adjustable-circle",
        "delete": "bi bi-trash3",
        "delete_selected": "bi bi-trash3",
        "dismiss": "bi bi-x",
        "doc": "bi bi-file-earmark-word",
        "docx": "bi bi-file-earmark-word",
        "edit": "bi bi-pencil-square",
        "error": "bi bi-x-circle",
        "export": "bi bi-arrow-down-circle",
        "export_admin_action": "bi bi-arrow-down-circle",
        "export-all": "bi bi-arrow-down-circle-fill",
        "file-check": "bi bi-file-earmark-check",
        "filter": "bi bi-filter-circle",
        "forward": "bi bi-chevron-double-right",
        "help": "bi bi-question-circle",
        "hide": "bi bi-eye-slash",
        "history": "bi bi-clock-history",
        "import": "bi bi-cloud-download",
        "info": "bi bi-info-circle",
        "link": "bi bi-link-45deg",
        "list-view": "bi bi-card-list",
        "login": "bi bi-box-arrow-left",
        "logout": "bi bi-box-arrow-in-right",
        "map": "bi bi-globe-americas",
        "map-location": "bi bi-geo-alt",
        "map-cross": "bi bi-crosshair",
        "pdf": "bi bi-filetype-pdf",
        "people": "bi bi-people",
        "play": "bi bi-play-circle",
        "print": "bi bi-printer",
        "remove": "bi bi-eraser",
        "report": "bi bi-printer",
        "rewind": "bi bi-chevron-double-left",
        "save": "bi bi-save",
        "schedule": "bi bi-journal-check",
        "search": "bi bi-search",
        "show": "bi bi-eye",
        "telephone": "bi bi-telephone",
        "theme-auto": "bi bi-circle-half",
        "theme-light": "bi bi-sun-fill",
        "theme-dark": "bi bi-moon-stars-fill",
        "user": "bi bi-person-fill",
        "viewsite": "bi bi-globe2",
        "xls": "bi bi-file-earmark-excel",
        "xlsx": "bi bi-file-earmark-excel",
        "xml": "bi bi-filetype-xml",
    },
}

ADMIN_CHANGEABLES = [
    "CHECK_AS_SWITCH",
    "FILTER_STYLE",
    "FIELDSET_STYLE",
    "INLINESET_STYLE",
    "BADGERIZE_FACETS",
]
